### ISSUE TITLE
CreateImageWizard: Just indicate you have an activation key on the review step, don't show the dots

### ISSUE THREAD

**Issue by Gundersanne** [RedHatInsights/image-builder-frontend#196]
![image](https://user-images.githubusercontent.com/11140201/118520373-5101f100-b73a-11eb-9711-3145ddb608da.png)

Instead of ••••••••••, have "You have an activation key!" or something similar?

**Comment by ochosi** [comment]
Maybe a check emoji would actually work fine too? :heavy_check_mark:

**Comment by Gundersanne** [comment]
ooh @katierik thoughts on the emoji?

**Comment by katierik** [comment]
TBH I think we can just show the name of the activation key - its not a secret!

**Comment by teg** [comment]
Should show it in the input too then, right?

I find it odd that the key isn't secret, but oh well :)

**Comment by katierik** [comment]
Yah - We should show it in the input. 
The activation keys used to be only shown to org admins but are being (or have already been) updated so that all logged in users on an account can see them. We're also going to be showing the keys on HCC (console.redhat.com) though Red Hat connector.

They certainly aren't "proclaim this value widely" items, but they're not passwords. At this point the user should be able to see which one they used with no problem.
