### ISSUE TITLE
Missing from nav-bar in stage

### ISSUE THREAD

**Issue by teg** [RedHatInsights/image-builder-frontend#380]
It appears Image Builder is not in the nav-bar in stage, even though the app works if you access it directly
<img width="668" alt="Screenshot 2021-10-28 at 18 35 42" src="https://user-images.githubusercontent.com/5409/139306678-3a249643-4fcd-4319-8331-48be3e25f626.png">
.

**Comment by jkozol** [comment]
For me, Image Builder does appear in the nav but in the wrong spot. I am confused about why it isn't displaying in the operations section since the [config file](https://github.com/RedHatInsights/cloud-services-config/blob/de2ab818d5c757c2c1e7c4ae6c6cfb5313d7d444/main.yml#L457) places it there. @Gundersanne any thoughts? I can ping the consoledot team if you don't spot anything obviously wrong.

![Screenshot from 2021-11-15 20-28-48](https://user-images.githubusercontent.com/11712857/141842282-c7529a8b-2f41-4c7b-9f76-daba3d369de9.png)

**Comment by jkozol** [comment]
Create an issue about this incorrect placement here: https://github.com/RedHatInsights/cloud-services-config/issues/970

**Comment by jkozol** [comment]
Fix pending in https://github.com/RedHatInsights/cloud-services-config/pull/971

**Comment by jkozol** [comment]
This is now fixed
