### ISSUE TITLE
Add id to each step in the wizard

### ISSUE THREAD

**Issue by Gundersanne** [RedHatInsights/image-builder-frontend#642]
Used for gathering some behavioural data. Format: #wizard-$step(-$substep).

**Comment by andreasn** [comment]
It needs to go inside the child of pf-c-wizard__main-body, because that is what tends to change between the steps as far as I can see.
So just to try out the syntax: #wizard-target-aws, #wizard-target-msazure, #wizard-systemconfiguration-filesystem, #wizard-systemconfiguration-packages etc.

I checked out the code, but unfortunately it's way too much react for me, so I would need to ask someone for a favor.
